---
abstract: "Generating and Populating 'provides' in your META.yml"
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: 0.01000004
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.4007
  Scalar::Util: 0
  Test::Fatal: 0
  Test::More: 0.98
  lib: 0
configure_requires:
  Module::Build: 0.4007
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MetaProvides
no_index:
  directory:
    - corpus
    - t/lib
provides:
  Dist::Zilla::MetaProvides::ProvideRecord:
    file: lib/Dist/Zilla/MetaProvides/ProvideRecord.pm
    version: 1.15000001
  Dist::Zilla::MetaProvides::Types:
    file: lib/Dist/Zilla/MetaProvides/Types.pm
    version: 1.15000001
  Dist::Zilla::Plugin::MetaProvides:
    file: lib/Dist/Zilla/Plugin/MetaProvides.pm
    version: 1.15000001
  Dist::Zilla::Role::MetaProvider::Provider:
    file: lib/Dist/Zilla/Role/MetaProvider/Provider.pm
    version: 1.15000001
requires:
  Dist::Zilla::Role::MetaProvider: 0
  Dist::Zilla::Util::EmulatePhase: 0.01000101
  Moose: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Readonly: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides/issues
  homepage: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides
  repository: https://github.com/kentfredric/Dist-Zilla-Plugin-MetaProvides.git
version: 1.15000001
x_BuiltWith:
  modules:
    Dist::Zilla::Plugin::Bootstrap::lib: 0.04000000
    Dist::Zilla::Plugin::MetaNoIndex: 4.300039
    Dist::Zilla::PluginBundle::Author::KENTNL: 1.8.3
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 1.7.2
    Dist::Zilla::Role::MetaProvider: 4.300039
    Dist::Zilla::Util::EmulatePhase: 0.01025802
    Dist::Zilla::Util::Test::KENTNL: 0.01015823
    File::Spec: 3.44
    IO::Handle: 1.35
    IPC::Open3: 1.15
    Module::Build: 0.4007
    Moose: 2.1005
    Moose::Role: 2.1005
    MooseX::Types: 0.38
    MooseX::Types::Moose: 0.38
    Pod::Coverage::TrustPod: 0.100002
    Readonly: 1.03
    Scalar::Util: 1.32
    Test::CPAN::Changes: 0.23
    Test::CPAN::Meta: 0.23
    Test::Fatal: 0.012
    Test::Kwalitee: 1.14
    Test::More: 0.98
    Test::Pod: 1.48
    Test::Pod::Coverage: 1.08
    lib: 0.63
    namespace::autoclean: 0.13
    perl: 'NA(skipped: perl)'
    strict: 1.08
    version: 0.9904
    warnings: 1.18
  perl:
    original: v5.19.3
    qv: 1
    version:
      - 5
      - 19
      - 3
  perl-config:
    gccversion: 4.7.2
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.11.0-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: 5.019003
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-Plugin-MetaProvides
          fallback: 0
          try_built: 1
          try_built_method: mtime
      name: Bootstrap::lib
      version: 0.04000000
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::KENTNL/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.38
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::KENTNL/MetaProvides::Package'
      version: 1.15000000
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.03000100
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.09
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: 2.06
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::KENTNL/Test::Compile'
      version: 2.033
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::KENTNL/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::KENTNL/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::KENTNL/NextRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/Prereqs/BundleDevelNeeds'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: recommends
      name: '@Author::KENTNL/Prereqs/BundleDevelRecommends'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/Prereqs/BundleDevelSuggests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl
      name: '@Author::KENTNL/Author::KENTNL::MinimumPerl'
      version: 1.8.3
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::KENTNL/CheckExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_master'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_release'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.021
    -
      class: Dist::Zilla::Plugin::Prereqs::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::MatchInstalled:
          applyto:
            - build.requires
            - build.recommends
            - build.suggests
            - test.requires
            - test.recommends
            - test.suggests
            - runtime.requires
            - runtime.recommends
            - runtime.suggests
            - configure.requires
            - configure.recommends
            - configure.suggests
            - develop.requires
            - develop.recommends
            - develop.suggests
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          applyto_relation:
            - requires
            - recommends
            - suggests
          modules:
            - Module::Build
            - Test::More
            - Dist::Zilla::PluginBundle::Author::KENTNL
      name: '@Author::KENTNL/Prereqs::MatchInstalled'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: suggests
      name: RuntimeSuggests
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: suggests
      name: TestSuggests
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
x_authority: cpan:KENTNL
